# Site settings
title: This is me # site title
description: >- # site description
  I build tools and break into applications.
lang: en-US # default lang
timezone: Asia/Kolkata # set your timezone
image: assets/img/rick.png # This image used for Open Graph more info https://ogp.me/
repo: https://dixitaditya.com/ # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: This is me ^ # author name
  bio: >- # tell to the world
    I'm Aditya. Check out my <a href="https://blog.dixitaditya.com/" target="_blank" rel="noopener">blog</a>
  username: username # general username
  github: az0mb13 # github username
  twitter: zombie007o # twitter username
  facebook: facebook_username # facebook username
  email: hi@dixitaditya.com # email adress
  avatar: /assets/img/rick.png # change with your own avatar

# URL settings
url: "https://dixitaditya.com" #
baseurl:
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
